require 'net/http'
require 'uri'

module Net
  module SMS
    module BulkSMS
      class Report
        #Status from: http://developer.bulksms.com/eapi/status_reports/get_report/
        STATUS_IN_PROGRESS          = 0
        STATUS_DELIVERED_UPSTREAM   = 10
        STATUS_DELIVERED_TO_MOBILE  = 11
        STATUS_DELIVERED_UPSTREAM_UNACKNOWLEDGED = 12
        STATUS_INTERNAL_FATAL_ERROR = 22
        STATUS_AUTH_FAILURE = 23
        STATUS_DATA_VALIDATION_FAILURE = 24
        STATUS_UNSUFICIENT_CREDITS = 25
        STATUS_UPSTREAM_CREDITS_UNAVAILABLE = 26
        STATUS_DAILY_QUOTA_EXCEEDED = 27
        STATUS_UPSTREAM_QUOTA_EXCEEDED = 28
        STATUS_MESSAGE_SENDING_CANCELED = 29
        STATUS_UNROUTABLE = 31
        STATUS_BLOCKED = 32
        STATUS_CENSORED = 33
        STATUS_TEMPORARILY_UNAVAILABLE = 40
        STATUS_GENERIC_FAILURE = 50
        STATUS_PHONE_DELIVERY_FAILED = 51
        STATUS_NETWORK_DELIVERY_FAILED = 52
        STATUS_MESSAGE_EXPIRED = 53
        STATUS_FAILED_ON_REMOTE_NETWORK = 54
        STATUS_REMOTELY_BLOCKED = 55
        STATUS_REMOTELY_CENSORED = 56
        STATUS_FAULT_ON_HANDSET = 57
        STATUS_TRANSIENT_UPSTREAM_FAILURE = 60
        STATUS_UPSTREAM_STATUS_FAILURE = 61
        STATUS_UPSTREAM_CANCEL_FAILED = 62
        STATUS_QUEUED_FOR_RETRY_AFTER_TEMPORARY_DELIVERY_FAILURE = 63
        STATUS_QUEUED_FOR_RETRY_AFTER_TEMPORARY_DELIVERY_HANDSET_FAULT = 64
        STATUS_UNKNOWN_UPSTREAM_STATUS = 70
      end
    end
  end
end